### ISSUE TITLE
.DS_Store in Lesson "Make parallel commits", commit nr. 3

### ISSUE THREAD

**Issue by derphilipp** [git-learning-game/oh-my-git#26]
It seems to me like an oversight: a .DS_Store file made its way into lession "Make parallel commits", commit Nr. 3
![image](https://user-images.githubusercontent.com/429154/108963089-f6488400-7679-11eb-92fa-7791283fe228.png)

**Comment by blinry** [comment]
Thanks for reporting! This is super interesting, because I have no idea where that file might come from. I think this is a macOS-specific file, are you testing on a Mac?

Did you open the level directory (`.../Oh My Git/tmp/repos/yours`) in a graphical file browser, by any chance?

Is this reproducible?

**Comment by derphilipp** [comment]
Unfortunately this seems not to be reproducible;
I am not 100% certain i did NOT open it up in a graphical browser, so I guess we could close it for now;
