### ISSUE TITLE
Instructions in "Moving branches around" are unclear

### ISSUE THREAD

**Issue by UweSauter** [git-learning-game/oh-my-git#77]
One way to complete the level is to remove the `coffee` and `baguette` branches, then checking out the end ot each line and re-create a new branch with correct name. Then check out the `donut` branch, change the file and commit.

From my understanding of the instructions, this is not the way it should be done. Either I misunderstand the instructions or they should be rephrased.

PS: I'm also missing a level that explains how to remove files from later commits when checking out a previous commit.

**Comment by benjamir** [comment]
I'm stuck too. What's the aim? I corrected the branches for "coffee" and "baguette" via "git reset --hard" but don't know what to do for "donut" -- "The donut branch is in the right place"... I tried the solution proposed by @UweSauter and it doesn't work for me (git checkout donut, edit "you", git commit -m "..."), I tried moving the branch "donut" around and back to the original commit, tried merging all branches (because of the "git merge" card) but the the "Did you eat a donut" never gets green.

Apart from that an interesting teaching tool so far.

**Comment by benjamir** [comment]
Okay, after reading the other issues and looking into the winning conditions there seems to be a repeated pattern: some winning conditions depend too much on language or non-obvious details that aren't relevant to learning git -- excuse me when that sounds very negative, I honestly think the overall approach is fun and worthwhile.
Because the format of the winning conditions is easily readable, with help from the community this should be just a bit of polish and nothing fundamental. Again, congrats for creating oh-my-git!

**Comment by blinry** [comment]
Thanks for pointing this out! :) We tried to rephrase/extend the level description to hopefully get you un-stuck! And we agree, @benjamir, getting lots of help from y'all on how to improve the levels would be great! Feel free to send PRs if you can think of further improvements, for example!

**Comment by estekadigital** [comment]
I am stuck on donut too, this is what i did:

git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
git checkout donut
vi you (and modify the file)
git add you
git commit -m "You eat the donut"

But donut never gets green, what am I doing wrong ?

**Comment by estekadigital** [comment]
> I am stuck on donut too, this is what i did:
> 
> git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
> git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
> git checkout donut
> vi you (and modify the file)
> git add you
> git commit -m "You eat the donut"
> 
> But donut never gets green, what am I doing wrong ?

Ok, i made it.. it was "You ate a donut"

**Comment by Brittreg** [comment]
> > I am stuck on donut too, this is what i did:
> > git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
> > git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
> > git checkout donut
> > vi you (and modify the file)
> > git add you
> > git commit -m "You eat the donut"
> > But donut never gets green, what am I doing wrong ?
> 
> Ok, i made it.. it was "You ate a donut"
THANK YOU

**Comment by Lauro235** [comment]
Really cool name. Any chance you could clarify the description for this level? It feels a bit cryptic and detracts from the clear and direct learning benefits of the game.

**Comment by Flomasta** [comment]
> > I am stuck on donut too, this is what i did:
> > git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
> > git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
> > git checkout donut
> > vi you (and modify the file)
> > git add you
> > git commit -m "You eat the donut"
> > But donut never gets green, what am I doing wrong ?
> 
> Ok, i made it.. it was "You ate a donut"

Oh, man! Thank you so much, i've spent about couple hours to figure out what was wrong. I thought that i was wrong in some ways to resolve the problem, but now I see that there is not quite clear task. If any developer see this, please fix it.

**Comment by hairywookster** [comment]
Although this issue is closed it might be easier to understand what the game is expecting.
- it wants you to eat/ate the donut on the donut branch.
- it wants the coffee branch to be related to the coffee actions/journey
- it wants the baguette branch to be related to the baguette actions/journey

So the starting point is really 
- the coffee and baguette branches need swapped w.r.t. the branch names point to the wrong final commits on those two branches - the journeys on these branches relate to the opposite branch name. This is not made entirely clear by the instructions/intro text but taking a step back it becomes obvious.
- the donut branch is fine but the contents of the text file need updated to reflect that the donut was "eat" or "ate"

So to solve using the commands introduced thus far, rather than commands not yet introduced, it becomes
- git checkout coffee
- git reset --hard <id of the commit baguette is pointing to>

- git checkout baguette
- git reset --hard <id of the final commit in what was the original coffee branch>

- git checkout  donut
- edit the file
- git add . ; git commit

**Comment by MaritanaAlves** [comment]
> > I am stuck on donut too, this is what i did:
> > git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
> > git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
> > git checkout donut
> > vi you (and modify the file)
> > git add you
> > git commit -m "You eat the donut"
> > But donut never gets green, what am I doing wrong ?
> 
> Ok, i made it.. it was "You ate a donut"

Thank you very much!! I spent hours in this lesson and I couldn't solve it , so I finally found your answer

**Comment by danmoraisc** [comment]
Mine only solved like this:
  
  - git checkout donut
  ~ I modified the last line to file 'you': You have a donut. -> You ate a donut. (other sentences didn't work.)
  - git add .; git commit -m 'You ate a donut'

**Comment by Ibrahim-official** [comment]
> I am stuck on donut too, this is what i did:
> 
> git branch -f baguette 801753600b5989547af81324f5d4cea51a218992 git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6 git checkout donut vi you (and modify the file) git add you git commit -m "You eat the donut"
> 
> But donut never gets green, what am I doing wrong ?


Its super simple once u get it, its bit like riddle:
First, git checkout donut
open you file, you get ths:

You do not have a baguette.

You do not have coffee.

You have a donut.

NOW just change "have" in third line to "ate" making the line "You ate a donut ."
Then just save it and u r done

**Comment by arthur1573** [comment]
> > I am stuck on donut too, this is what i did:
> > git branch -f baguette 801753600b5989547af81324f5d4cea51a218992
> > git branch -f coffee f1cb88ca5f2f3b866fe0474fe0a39ea2c15eb2b6
> > git checkout donut
> > vi you (and modify the file)
> > git add you
> > git commit -m "You eat the donut"
> > But donut never gets green, what am I doing wrong ?
> 
> Ok, i made it.. it was "You ate a donut"


that is not friendly for a noob to learn git/english.....

**Comment by arthur1573** [comment]
git checkout coffee
git reset --hard 3dc8

git checkout baguette
git reset --hard 8b2b

git checkout donut
double click file 'you' to edit : "you ate a donut"
git add .
git commit
'hahahahaahaha'

done

**Comment by Tahmid-kabir-addin** [comment]
First of all, look at the below image: the baguette branch head is **not in the right place.**
![image](https://github.com/user-attachments/assets/4e52339e-3be5-4440-bcac-ac4f2f374f30)
The same goes for the coffee branch head:
![image](https://github.com/user-attachments/assets/f97f4c1c-a5de-4ab2-835a-35307a86e2b0)
Now, You need to switch the branch heads:
```
git checkout baguette
git branch -f coffee
```
![image](https://github.com/user-attachments/assets/76d446a8-edb0-454e-93a2-5715812728a5)
```
git checkout <previous coffee head commit id>
git branch -f baguette
```
![image](https://github.com/user-attachments/assets/7bf2d045-75fe-4d10-b5a5-46c845d7bab9)
```
git checkout donut
# change the last line to You ate a donut
git add .
git commit -m 'your commit message'
```
![image](https://github.com/user-attachments/assets/47cd4c2c-ab62-4af5-863a-9faa5e1b35da)
