### ISSUE TITLE
level "Reordering events" unsolvable

### ISSUE THREAD

**Issue by linuzer** [git-learning-game/oh-my-git#79]
I'm unable to solve that level on MacOS Catalina 10.15.7

After digging into the source-code, I suspect, that it has to do with the winning-scenario:

`{ git log main --oneline | LC_ALL=en_US.utf8 grep -Pz "shoes[\s\S]*pants[\s\S]*underwear"; } && { test "$(git log main --oneline | wc -l)" -eq 5; }`

If I try to execute the first part in the built-in terminal, it shows up, that the grep parameters "-P" and "-z" doesn't seem to exist in my environment.

But anyway, a very cool and helpful game!!!

**Comment by apiening** [comment]
Oh that's interesting: I was trying to solve this level by doing a `git reset --hard` to `The Beginning` and then cherry-picked the commits in the order given by the lines in the text file over and over again. I then decided to look for help here expecting that I didn't understand the challenge of this mission correctly.

I hope this issue will be fixed soon, since there is a PR already.

**Comment by chstdu** [comment]
I am stuck here too. (I tried both: rebase and cherry-pick solution) How do I update the app?

**Comment by blinry** [comment]
We'll release a version 0.6.4 later today, which includes this fix! :)
